export const SAVE_NEW_DOWNLOAD_URL = 'SAVE_NEW_DOWNLOAD_URL';
export const RESTORE_DOWNLOAD_URL = 'RESTORE_DOWNLOAD_URL';

export const DOWNLOAD_QUERIES_CSV_REQUEST = 'DOWNLOAD_QUERIES_CSV_REQUEST';
export const DOWNLOAD_QUERIES_CSV_SUCCESS = 'DOWNLOAD_QUERIES_CSV_SUCCESS';
export const DOWNLOAD_QUERIES_CSV_FAILURE = 'DOWNLOAD_QUERIES_CSV_FAILURE';